/*global systemDictionary:true */
'use strict';

systemDictionary = {
  'viessmannapi adapter settings': {
    en: 'Adapter settings for viessmannapi',
    de: 'Adaptereinstellungen für viessmannapi',
    ru: 'Настройки адаптера для viessmannapi',
    pt: 'Configurações do adaptador para viessmannapi',
    nl: 'Adapterinstellingen voor viessmannapi',
    fr: "Paramètres d'adaptateur pour viessmannapi",
    it: "Impostazioni dell'adattatore per viessmannapi",
    es: 'Ajustes del adaptador para viessmannapi',
    pl: 'Ustawienia adaptera dla viessmannapi',
    'zh-cn': 'viessmannapi2的适配器设置',
  },
  'Update device status (in minutes).': {
    en: 'Update device status (in minutes).',
    de: 'Gerätestatus aktualisieren (in Minuten).',
    ru: 'Обновить статус устройства (в минутах).',
    pt: 'Atualize o status do dispositivo (em minutos).',
    nl: 'Apparaatstatus bijwerken (in minuten).',
    fr: "Mettre à jour l'état de l'appareil (en minutes).",
    it: 'Aggiorna lo stato del dispositivo (in minuti).',
    es: 'Actualice el estado del dispositivo (en minutos).',
    pl: 'Zaktualizuj stan urządzenia (w minutach).',
    'zh-cn': '更新设备状态（以分钟为单位）。',
  },
  'Update gateway events (in minutes).': {
    en: 'Update gateway events (in minutes).',
    de: 'Gateway-Ereignisse aktualisieren (in Minuten).',
    ru: 'Обновить события шлюза (в минутах).',
    pt: 'Atualizar eventos de gateway (em minutos).',
    nl: 'Gatewaygebeurtenissen bijwerken (in minuten).',
    fr: 'Mettre à jour les événements de passerelle (en minutes).',
    it: 'Aggiorna gli eventi del gateway (in minuti).',
    es: 'Actualice los eventos de la puerta de enlace (en minutos).',
    pl: 'Zaktualizuj zdarzenia bramy (w minutach).',
    'zh-cn': '更新网关事件（以分钟为单位）。',
  },
  'Viessmannapi Password': {
    en: 'Viessmannapi Password',
    de: 'Viessmannapi Passwort',
    ru: 'Пароль Viessmannapi',
    pt: 'Senha Viessmannapi',
    nl: 'Viessmannapi-wachtwoord',
    fr: 'Mot de passe Viessmannapi',
    it: 'Password Viessmannap',
    es: 'Contraseña de Viessmannapi',
    pl: 'Hasło Viessmannapi',
    'zh-cn': 'Viessmannapi 密码',
  },
  'Allowlist of IDs which allow to update to prevent rate limit with ViCare Einzelraumsteuerung. Example: 0,HeatDemandControl':
    {
      en: 'Allowlist of IDs which allow to update to prevent rate limit with ViCare Einzelraumsteuerung. Example: 0, HeatDemandControl',
      de: 'Erlaubnisliste der IDs, die zu aktualisieren sind, um Ratenlimit mit ViCare Einzelraumsteuerung zu verhindern. Beispiel: 0, HeatDemandControl',
      ru: 'Список разрешений, которые позволяют обновлять, чтобы предотвратить лимит скорости с ViCare Einzelraumsteuerung. Пример: 0, HeatDemandControl',
      pt: 'Lista de IDs que permitem atualizar para evitar o limite de taxa com ViCare Einzelraumsteuerung. Exemplo: 0, HeatDemandControl',
      nl: "Staatslijst van ID's die kunnen updaten om de limiet te voorkomen met ViCare Einzelraumsteuerung. Vertaling:",
      fr: 'Liste des ID qui permettent de mettre à jour pour prévenir la limite de taux avec ViCare Einzelraumsteuerung. Exemple: 0, HeatDemandControl',
      it: 'Consentire lista di ID che permettono di aggiornare per prevenire il limite di tasso con ViCare Einzelraumsteuerung. Esempio: 0, HeatDemandControl',
      es: 'Permiso de identificaciones que permiten actualizar para evitar límite de tarifas con ViCare Einzelraumsteuerung. Ejemplo: 0, HeatDemandControl',
      pl: 'Allowlist of IDs, które umożliwiają aktualizację, aby zapobiec ograniczaniu tempa z ViCare Einzelraumsteuerung. Przykład: 0, HeatDemandControl',
      uk: 'Список ідентифікаторів, які дозволяють оновити для запобігання обмеження швидкості з ViCare Einzelraumsteuerung. Приклад: 0, HeatDemandControl',
      'zh-cn': '允许更新的开发者名单,以防止与维克雷·埃斯利拉姆特森松的汇率限制。 例:00',
    },
};
